### ISSUE TITLE
Relationship to cl-ipfs-api ?

### ISSUE THREAD

**Issue by Ambrevar** [JadedCtrl/cl-ipfs-api2#8]
Hello,

What's the relationship between this repo and https://github.com/wemeetagain/cl-ipfs-api ?

Is the latter deprecated?  Are there pros and cons?

**Comment by JadedCtrl** [comment]
From what I remember, I started cl-ipfs-api2 because some functions of cl-ipfs-api didn't work on my system (or were inconvenient). I don't know which project would be better for you, but you might have more luck with cl-ipfs-api2, being more freshly updated.

I'm not updating cl-ipfs-api2 myself anymore, but I will accept good patches.

**Comment by Ambrevar** [comment]
Alrighty, thanks for the heads up!
